sudo: required
language: java
install: true
jdk:
  - oraclejdk8

#required for launch4j to run
before_script:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386

script:
  - mvn install -X
  - mvn clean package

after_success:
  - mvn test jacoco:report coveralls:report

deploy:
  - provider: releases
    api_key:
      secure: "MB0WOVvAm07Csmt1o+9Wqb2l6nnEuvRS4eSHqTVDacdz4/HZLYhd04dtSsP4LIi3flN5pgPHUt2xNv7TfgaA1/xK9QXHpnA02QA15q1Zx8H2XxiDZQPy1JD04AVGve
      jZ0+SFZadM5CyRZt1Oe3j4+fl+RsZuC6OLmimN+Mk8jwjyjtckEKyRqNvjJ+rCpjOHQv2a+0R241CNSfilamOR8zFxtxsbGziyPns0kpi/nEDn9Yjbk6XWc5P69OHlHDT9MnXPW65
      zVX5fc+eLRHlRxcJD/zSLC/chvRVo8WsXgahpr4U2uCkBWzwdNwnCQjokd+sRGGv5Vf1SBMHH6cLZcso18cgCci/Zsi7rgVOOCdNb+WcAl4fdP30Iz31hvdwxuRHILja+6JiCu272
      aDkxayHOk7TjGNPbBUwt7w01ChU+hKOGSw8vaT1NByuur84IkfFdF3FD8LzpRPbqG2SBIxnctZT6OqQaAs/6xyKxXWejNwIA+qRrOLe9TJ889FUlsEeiKBcDWKc99nBi9i4fw4uHt
      yAD9+VCF3/MVw+EzK1SgbzLGw1tUENPTPTfd6UCektWFknF62VKB+zi4Nl+t5OgYeUbHDUxQkwvOyMKF5NLk1PYT6cFIQwMdA0i/WMYoK8jGOCm46jasKjH3SkOyNp0mMz/XEmJCY
      b2+Tce5KM="
    file_glob: true
    file:
      - "target/dice-*.jar"
      - "target/dice.exe"
    skip_cleanup: true
    on:
      branch: master
      tags: true

notifications:
  slack:
    secure: "hp09fUWRqUe/OH8A2/9Tp7KO9v568UG3RW7NPBvQH4vpFKb7HMgP6p+r1x0QdiioapIva/Mntzsd1TM11kSzmWX8dTS9UqYBFMpdxEBu+CILu4ttiQwEVqcwt95Igl7ZtSgjJrn/Z/s2YsGNtU2RS1GrmCZLlpT7ym2ILlgtfx1PNkCHgTZlxk1hmtbFPk/CoC5eg2mUnyPw/ssP76vYvyWc6y3UrIFAkh5UFIK/74rOKsAEsHPOPwPKbISVM5YsM/TQz3018X4np1EjWwEgLIqYtn6CPsJdQHzSAGkwJ8gsLHKizezyj0/MW1DV/U0WQgsywqTPoDqIikrhWk7lPqdD5cHmJMVkkO1axCSu4pXbKfYd+NOGWBciRkpLqevpOjOvcgBg2MEY3mUxEb99Aq7WGaWzgYGqghgZoPHPawQ4dz5+oIBb5KN7sTaXhvDPYTZh6pzgm125Vsquc27b/mo9ma2bgjXI0MV7E2fkXN1oZXe9GxPYnWFK8WdlxA+t6kp5/9d/FTtIbTgdd2k0JRozV+n4j0Kq3pNLJCQ/cvJar+w/Xo9R/iixbHfBVOGIJv5Rk+DqUJFzKJ/95B+EOW5+1R/oyq4lrHBUDJHXIicDhepBWzbBoL+kV5zSrF+R03iLWUMineSOXJpvbJhC28+xE/GRQGImoaU6KgB6stw="
  email: false